name = "ebms-worker"
main = "apps/worker/src/index.ts"
compatibility_date = "2026-03-09"
workers_dev = true

[vars]
CONTRACT_SIGNING_SECRET = "replace-me-in-prod"
SYNC_API_KEY = "replace-sync-key"

[[d1_databases]]
binding = "DB"
database_name = "asd"  # <--- "ebms"-ийг "asd" болгож соль
database_id = "2b2d939e-3fcf-4d88-a21c-2f94b4750c01" 

[[kv_namespaces]]
binding = "EBMS_KV"
id = "d3a1734ab928493da60dad0a0811ea10"

[[r2_buckets]]
binding = "CONTRACTS_BUCKET"
bucket_name = "company-ebms-contracts"

[observability]
enabled = true
